name: Wheel
description: build a python cryptography wheel on winarm

on:
  push:
    branches: 
      - '*'
  pull_request:
    branches: 
      - '*'
  workflow_dispatch:

jobs:
  build-wheel:
    strategy:
      fail-fast: false
    runs-on: windows-11-arm
    name: Build wheel on Windows/ARM
    env: 
      VCPKG_ROOT: 'C:\VCPKG'
    steps:
      - name: Show VCPKG_ROOT
        run: |
            echo $env:VCPKG_ROOT
