name: Wheel
description: build a python cryptography wheel on winarm

on:
  push:
    branches: 
      - '*'
  pull_request:
    branches: 
      - '*'
  workflow_dispatch:

jobs:
  build-wheel:
    strategy:
      fail-fast: false
    runs-on: windows-11-arm
    name: Build wheel on Windows/ARM
    env: 
      VCPKG_ROOT: 'C:\vcpkg'
      OPENSSL_DIR: 'C:\vcpkg\installed\arm64-windows-static'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          architecture: 'arm64'
      - name: Setup virtual env
        run: |
          python -m venv ./venv
      - name: install dependencies
        run: |
          vcpkg install openssl:arm64-windows-static
          vcpkg integrate install
      - name: Build crypto wheel
        shell: pwsh
        run: |
          ./venv/Scripts/python -m pip install --upgrade pip
          ./venv/Scripts/python -m pip install -r requirements.txt
