name: Wheel
description: build a python cryptography wheel on winarm

on:
  push:
    branches: 
      - '*'
  pull_request:
    branches: 
      - '*'
  workflow_dispatch:

jobs:
  build-wheel:
    strategy:
      fail-fast: false
    runs-on: windows-11-arm
    name: Build wheel on Windows/ARM
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          architecture: 'arm64'
      - name: Setup virtual env
        run: |
          python -m venv ./venv
      - name: Setup vcpkg and install dependencies
        run: |
          git clone https://github.com/microsoft/vcpkg.git $env:VCPKG_ROOT
          cd $env:VPKG_ROOT
          ./bootstrap-vcpkg.bat -disableMetrics
          ./vcpkg.exe install openssl
        env:
          VCPKG_ROOT: 'C:\vcpkg'
      - name: Build crypto wheel
        shell: pwsh
        run: |
          ./venv/Scripts/python -m pip install --upgrade pip
          ./venv/Scripts/python -m pip install -r requirements.txt
